### ISSUE TITLE
How about prune the dependency of `k8s.io/kubernetes`

### ISSUE THREAD

**Issue by STRRL** [kubewharf/kubebrain#4]
### What would you like to be added?

I found that the only usage of `k8s.io/kubernetes` is here:

https://github.com/kubewharf/kubebrain/blob/793d0cfde538ab9d05995efdc54e9e594fb44d15/cmd/main.go#L56

I am very pleased to contribute if my proposal is accepted.

### Why is this needed?

- It would reduce lots of time of preparing the dev environment and also the time of building kubebrain. 
- it would reduce the concern about "which version of `k8s.io/kubernetes` should we use" , and many related go modules replace issues

You know, the much better dev experience. :P

**Comment by divanodestiny** [comment]
Thanks for your advisor. Please feel free to file an PR. If you are busy,  i will solve it tonight.

**Comment by STRRL** [comment]
I would give it a try very soon. :D
